# Generated by Django 3.0.3 on 2020-08-16 00:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('role', models.CharField(choices=[('G', 'General User'), ('A', 'Admin User')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=5)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='entryImages/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>'), size=5)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelEntries.User')),
            ],
        ),
    ]
