# Generated by Django 3.0.3 on 2020-08-16 20:20

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('travelEntries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='images',
        ),
        migrations.AlterField(
            model_name='entry',
            name='descriptions',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), size=5),
        ),
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entryImages/<django.db.models.fields.related.ForeignKey>')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelEntries.Entry')),
            ],
        ),
    ]
