# Generated by Django 3.0.3 on 2020-10-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelEntries', '0003_auto_20200903_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='entryimage',
            name='description',
            field=models.CharField(default='No Description Given', max_length=500),
        ),
    ]
